### ISSUE TITLE
Consider adding the app to the community list

### ISSUE THREAD

**Issue by alexAubin** [Guigo-/medusa_ynh#1]
Hello !

This is a friendly notice from the Yunohost Apps team : our tool noticed that your app is pretty interesting but is not listed in the [community list](https://github.com/YunoHost/apps/blob/master/community.json) !

Please consider making a pull request to add it, such that people can easily learn about its existence from [this page](https://yunohost.org/#/apps). If you declare your app as working, you might also benefit from [automatic tests on the app C.I.](https://ci-apps.yunohost.org/).

It is relevant to add your app to the list even if it's not working or unmaintained since it might still help people who might want to continue packaging the app. Just be sure to correctly flag it as notworking/unmaintained.

Checkout the README to learn [how to add your app to the list](https://github.com/YunoHost/apps#how-to-add-your-app-to-the-community-list) (should take only a few minutes).

Datalove <3,

The YunoHost team

**Comment by guigot** [comment]
Hello,

I already forked the repository YunoHost/apps to modify the file community.json. I want to test the installation with the latest version of medusa with ynh-dev. Give me a few days and I'll make the pull request.

Also, thank you for making such a project.

**Comment by alexAubin** [comment]
Alrighty :+1: If you want, we can manually trigger a build on the dev CI so that you would get result from the test chain : https://ci-apps-dev.yunohost.org/jenkins/

Thanks for working on this app :tada: :smile:

**Comment by guigot** [comment]
Thanks for your proposal, I wanted to test some Medusa features more than the installation itself and it's done. I did the pull request, I hope everything will be fine !

**Comment by frju365** [comment]
Could you move your repo to the Yunohost-Apps Orga. The goal is to have all the repos in a single place. You will have ofc rights on the repo (it doesn't change anything). I sent you an invitation to join Yunohost-Apps orga.

**Comment by guigot** [comment]
I accepted the invitation and transfered the ownership to YunoHost-Apps.

**Comment by frju365** [comment]
Nice thank you very much !

**Comment by frju365** [comment]
I close the issue.
